"use client";

import { useEffect, useState } from "react";
import { ExternalLink, Loader2, Sparkles } from "lucide-react";
import { fetchAiGenerated } from "@/services/aiGenerate";
import type { LiveResultItem, LiveSearchCategory } from "@/services/gemini/types";
import { Badge, Tag } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { formatMinutes } from "@/lib/format";

const MIN_QUERY_LENGTH = 3;

interface Props {
  category: LiveSearchCategory;
  query: string;
  heritages: string[];
  city: string;
  state: string;
  /**
   * Only fetch when the parent has confirmed there's a specific subject
   * (not just profile chit-chat) AND nothing local or live already answered
   * it — generating an example when a real one already exists would just
   * be redundant, unverified noise next to something better.
   */
  enabled: boolean;
}

const PROVIDER_LABEL: Record<string, string> = { gemini: "Gemini", groq: "Groq" };

/**
 * Renders an AI-synthesized example — a full recipe, or plain-language
 * guidance for finding a real community/place/event/program — when the
 * local dataset and live web search both came up empty for a specific
 * request. Always visually and textually distinct from "Live results from
 * the web": this is explicitly NOT a claim that a real listing was found.
 */
export function AiGeneratedSection({ category, query, heritages, city, state, enabled }: Props) {
  const [loading, setLoading] = useState(false);
  const [item, setItem] = useState<LiveResultItem | null>(null);
  const [provider, setProvider] = useState<string | undefined>(undefined);
  const [configured, setConfigured] = useState(true);

  useEffect(() => {
    if (!enabled || query.trim().length < MIN_QUERY_LENGTH) {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- clearing stale results when disabled/query shrinks is part of syncing with the fetch below
      setItem(null);
      return;
    }
    let cancelled = false;
    setLoading(true);
    fetchAiGenerated({ category, query, heritages, city, state }).then((res) => {
      if (cancelled) return;
      setConfigured(res.configured);
      setItem(res.generated && res.item ? res.item : null);
      setProvider(res.provider);
      setLoading(false);
    });
    return () => {
      cancelled = true;
    };
  }, [category, query, heritages, city, state, enabled]);

  if (!enabled || !configured || query.trim().length < MIN_QUERY_LENGTH) return null;
  if (!loading && !item) return null;

  return (
    <div className="mt-4 rounded-3xl border border-dashed border-berry/40 bg-berry-soft/30 p-4 md:p-5">
      <div className="flex items-center gap-2">
        <Sparkles className="h-4 w-4 text-berry" aria-hidden />
        <h3 className="text-xs font-bold uppercase tracking-wider text-berry-deep">
          Generated by AI{provider ? ` (${PROVIDER_LABEL[provider] ?? provider})` : ""}
        </h3>
        {loading ? <Loader2 className="h-3.5 w-3.5 animate-spin text-berry" aria-hidden /> : null}
      </div>
      <p className="mt-1 text-xs text-brown-muted">
        Not a real, verified result — an AI-generated example, since nothing matching this was found in the demo dataset or the live web. Double-check before relying on it, especially for allergies or ingredients.
      </p>

      {loading && !item ? (
        <div className="mt-3 h-32 animate-pulse rounded-2xl bg-white/50" />
      ) : item ? (
        <div className="mt-3 rounded-2xl border border-beige bg-cream p-4 shadow-soft">
          <div className="flex items-start justify-between gap-2">
            <h4 className="text-sm font-semibold text-brown">{item.name}</h4>
            {item.kind === "recipe" && item.difficulty ? <Badge tone="beige">{item.difficulty}</Badge> : null}
          </div>
          {item.kind === "recipe" && item.timeMinutes ? <p className="mt-1 text-xs text-brown-muted">{formatMinutes(item.timeMinutes)}</p> : null}
          <p className="mt-2 text-sm leading-relaxed text-brown-muted">{item.description}</p>

          {item.kind === "recipe" && item.ingredients?.length ? (
            <div className="mt-3">
              <p className="text-xs font-bold uppercase tracking-wide text-brown-faint">Ingredients</p>
              <ul className="mt-1.5 list-disc space-y-0.5 pl-4 text-sm text-brown-muted">
                {item.ingredients.map((ing, i) => (
                  <li key={i}>{ing}</li>
                ))}
              </ul>
            </div>
          ) : null}

          {item.kind === "recipe" && item.steps?.length ? (
            <div className="mt-3">
              <p className="text-xs font-bold uppercase tracking-wide text-brown-faint">Steps</p>
              <ol className="mt-1.5 list-decimal space-y-1 pl-4 text-sm text-brown-muted">
                {item.steps.map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ol>
            </div>
          ) : null}

          {item.tags.length ? (
            <div className="mt-3 flex flex-wrap gap-1">
              {item.tags.slice(0, 5).map((t) => (
                <Tag key={t}>{t}</Tag>
              ))}
            </div>
          ) : null}

          {item.externalUrl ? (
            <Button variant="outline" size="sm" className="mt-3" href={item.externalUrl} external iconRight={<ExternalLink className="h-3.5 w-3.5" aria-hidden />}>
              Search the web for this
            </Button>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}
